### Loading Libraries we will use in the project

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import plotly.express as px
import numpy as np
from statsmodels.tsa.stattools import adfuller, acf, pacf
import pandas as pd
from sklearn.preprocessing import Normalizer, MinMaxScaler, StandardScaler, RobustScaler
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import datetime
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
sns.set()

ModuleNotFoundError: No module named 'tensorflow'

### Importing scripts & modules

In [4]:
import os
import sys
sys.path.append(os.path.abspath(os.path.join('../scripts')))

In [5]:
from helper import MyHelper
import utility
import plots
Helper = MyHelper()

### Loading the data

In [6]:
train_PATH = "../data/train.csv"
test_PATH = "../data/test.csv"
store_PATH = "../data/store.csv"
sample_PATH = "../data/sample_submission.csv"

In [7]:
# the class has utility function we are going to use
Helper = MyHelper()

In [9]:
# we use our helper function to read csv data
train = Helper.read_csv(train_PATH)
test = Helper.read_csv(test_PATH)

>> file read as csv
>> file read as csv

In [11]:
Helper.percent_missing(train)

0.77

In [12]:
def get_feature(df):
    return df[["Date", "Sales"]]

In [13]:
def drop_closed(df):
    df = df[df['Open'] == 1]
    return df

In [14]:
def scaler(df, columns, mode="minmax"):
    if (mode == "minmax"):
        minmax_scaler = MinMaxScaler()
        return pd.DataFrame(minmax_scaler.fit_transform(df), columns=columns), minmax_scaler
    elif (mode == "standard"):
        scaler = StandardScaler()
        return pd.DataFrame(scaler.fit_transform(df), columns=columns), scaler
    elif (mode == "robust"):
        scaler = RobustScaler()
        return pd.DataFrame(scaler.fit_transform(df), columns=columns), scaler

In [15]:
def add_scaled_sales(df):
    scaled_sales, scaler_obj = scaler(df[["Sales"]], mode="minmax", columns=["scaled_sales"])
    df["scaled_sales"] = scaled_sales["scaled_sales"].to_list()
    return df, scaler_obj

In [16]:
def handle_outliers(df, col, method="lower_upper"):
        
        df = df.copy()
        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)

        lower_bound = q1 - ((1.5) * (q3 - q1))
        upper_bound = q3 + ((1.5) * (q3 - q1))

        if method == "mean":
            df[col] = np.where(df[col] < lower_bound,   df[col].mean(), df[col])
            df[col] = np.where(df[col] > upper_bound, df[col].mean(), df[col])

        elif  method == "mode":
            df[col] = np.where(df[col] < lower_bound,   df[col].mode()[0], df[col])
            df[col] = np.where(df[col] > upper_bound, df[col].mode()[0], df[col])
        else:
            df[col] = np.where(df[col] < lower_bound, lower_bound, df[col])
            df[col] = np.where(df[col] > upper_bound, upper_bound, df[col])

        return df

In [17]:
train["Sales"] = train["Sales"].astype("float")

In [18]:
data = drop_closed(train)
data = get_feature(data)
data = handle_outliers(data, "Sales")

KeyError: "['Date'] not in index"

In [19]:
data_agg = data.groupby("Date").agg({"Sales": "mean"})
helper.percent_missing(data_agg)
data_agg.describe()

KeyError: 'Date'

In [20]:
display(train.head())
display(train.describe())
display(train.info())

,Store,DayOfWeek,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,Year,Month,...,Dates,StoreType,Assortment,CompetitionDistance,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval,SalesperCustomer,CompetitionOpenSince
0,1,5,5263.0,555.0,1,1,0,1,2015,7,...,2015-07-31,c,a,1270.0,0,0.0,0.0,0,9.482883,82.0
1,1,4,5020.0,546.0,1,1,0,1,2015,7,...,2015-07-30,c,a,1270.0,0,0.0,0.0,0,9.194139,82.0
2,1,3,4782.0,523.0,1,1,0,1,2015,7,...,2015-07-29,c,a,1270.0,0,0.0,0.0,0,9.143403,82.0
3,1,2,5011.0,560.0,1,1,0,1,2015,7,...,2015-07-28,c,a,1270.0,0,0.0,0.0,0,8.948214,82.0
4,1,1,6102.0,612.0,1,1,0,1,2015,7,...,2015-07-27,c,a,1270.0,0,0.0,0.0,0,9.970588,82.0

,Store,DayOfWeek,Sales,Customers,Open,Promo,SchoolHoliday,Year,Month,Day,WeekOfYear,CompetitionDistance,Promo2,Promo2SinceWeek,Promo2SinceYear,SalesperCustomer,CompetitionOpenSince
count,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,844340.000000,1.017209e+06
mean,5.584297e+02,3.998341e+00,5.472856e+03,5.783493e+02,8.301067e-01,3.815145e-01,1.786467e-01,2.013832e+03,5.846762e+00,1.570279e+01,2.361551e+01,5.422034e+03,5.005638e-01,1.164767e+01,1.007011e+03,9.722615,4.114934e+01
std,3.219087e+02,1.997391e+00,3.323989e+03,3.483565e+02,3.755392e-01,4.857586e-01,3.830564e-01,7.773960e-01,3.326097e+00,8.787638e+00,1.443338e+01,7.706913e+03,4.999999e-01,1.532393e+01,1.005877e+03,2.550463,6.601545e+01
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.013000e+03,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,-3.100000e+01
25%,2.800000e+02,2.000000e+00,3.727000e+03,4.050000e+02,1.000000e+00,0.000000e+00,0.000000e+00,2.013000e+03,3.000000e+00,8.000000e+00,1.100000e+01,7.100000e+02,0.000000e+00,0.000000e+00,0.000000e+00,8.007077,0.000000e+00
50%,5.580000e+02,4.000000e+00,5.744000e+03,6.090000e+02,1.000000e+00,0.000000e+00,0.000000e+00,2.014000e+03,6.000000e+00,1.600000e+01,2.200000e+01,2.330000e+03,1.000000e+00,1.000000e+00,2.009000e+03,9.431414,1.600000e+01
75%,8.380000e+02,6.000000e+00,7.584000e+03,7.940000e+02,1.000000e+00,1.000000e+00,0.000000e+00,2.014000e+03,8.000000e+00,2.300000e+01,3.500000e+01,6.880000e+03,1.000000e+00,2.200000e+01,2.012000e+03,11.005882,7.300000e+01
max,1.115000e+03,7.000000e+00,1.404900e+04,1.485000e+03,1.000000e+00,1.000000e+00,1.000000e+00,2.015000e+03,1.200000e+01,3.100000e+01,5.200000e+01,7.586000e+04,1.000000e+00,5.000000e+01,2.015000e+03,51.694444,1.386000e+03

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 22 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Store                 1017209 non-null  int64
 1   DayOfWeek             1017209 non-null  int64
 2   Sales                 1017209 non-null  float64
 3   Customers             1017209 non-null  float64
 4   Open                  1017209 non-null  int64
 5   Promo                 1017209 non-null  int64
 6   StateHoliday          1017209 non-null  object
 7   SchoolHoliday         1017209 non-null  int64
 8   Year                  1017209 non-null  int64
 9   Month                 1017209 non-null  int64
 10  Day                   1017209 non-null  int64
 11  WeekOfYear            1017209 non-null  int64
 12  Dates                 1017209 non-null  object
 13  StoreType             1017209 non-null  object
 14  Assortment            1017209 non-null  object
 15  CompetitionDistance   1017209 non-null  float64
 16  Promo2                1017209 non-null  int64
 17  Promo2SinceWeek       1017209 non-null  float64
 18  Promo2SinceYear       1017209 non-null  float64
 19  PromoInterval         1017209 non-null  object
 20  SalesperCustomer      844340 non-null   float64
 21  CompetitionOpenSince  1017209 non-null  float64
dtypes: float64(7), int64(10), object(5)
memory usage: 170.7+ MB

None